{{- if .Values.logConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  # https://github.com/uber-go/zap/blob/aa3e73ec0896f8b066ddf668597a02f89628ee50/config.go
  zap-logger-config: |
    {
      "level": "{{ or .Values.logConfig.logLevel.global .Values.logLevel }}",
      "development": false,
      "disableStacktrace": true,
      "disableCaller": true,
      "sampling": {
        "initial": 100,
        "thereafter": 100
      },
      "outputPaths": [{{ include "karpenter.outputPathsList" . }}],
      "errorOutputPaths": [{{ include "karpenter.errorOutputPathsList" . }}],
      "encoding": "{{ or .Values.logConfig.logEncoding .Values.logEncoding }}",
      "encoderConfig": {
        "timeKey": "time",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "message",
        "stacktraceKey": "stacktrace",
        "levelEncoder": "capital",
        "timeEncoder": "iso8601"
      }
    }
  loglevel.controller: {{ or .Values.logConfig.logLevel.controller .Values.controller.logLevel }}
  loglevel.webhook: {{ or .Values.logConfig.logLevel.webhook .Values.webhook.logLevel }}
{{- end }}